// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: thanawy/v1/analytics.proto

package thanawyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "thanawy-backend/internal/proto/thanawy/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AnalyticsServiceName is the fully-qualified name of the AnalyticsService service.
	AnalyticsServiceName = "thanawy.v1.AnalyticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnalyticsServiceGetProgressSummaryProcedure is the fully-qualified name of the AnalyticsService's
	// GetProgressSummary RPC.
	AnalyticsServiceGetProgressSummaryProcedure = "/thanawy.v1.AnalyticsService/GetProgressSummary"
	// AnalyticsServiceGetWeeklyAnalyticsProcedure is the fully-qualified name of the AnalyticsService's
	// GetWeeklyAnalytics RPC.
	AnalyticsServiceGetWeeklyAnalyticsProcedure = "/thanawy.v1.AnalyticsService/GetWeeklyAnalytics"
)

// AnalyticsServiceClient is a client for the thanawy.v1.AnalyticsService service.
type AnalyticsServiceClient interface {
	GetProgressSummary(context.Context, *connect.Request[v1.GetProgressSummaryRequest]) (*connect.Response[v1.GetProgressSummaryResponse], error)
	GetWeeklyAnalytics(context.Context, *connect.Request[v1.GetWeeklyAnalyticsRequest]) (*connect.Response[v1.GetWeeklyAnalyticsResponse], error)
}

// NewAnalyticsServiceClient constructs a client for the thanawy.v1.AnalyticsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalyticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalyticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analyticsServiceMethods := v1.File_thanawy_v1_analytics_proto.Services().ByName("AnalyticsService").Methods()
	return &analyticsServiceClient{
		getProgressSummary: connect.NewClient[v1.GetProgressSummaryRequest, v1.GetProgressSummaryResponse](
			httpClient,
			baseURL+AnalyticsServiceGetProgressSummaryProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetProgressSummary")),
			connect.WithClientOptions(opts...),
		),
		getWeeklyAnalytics: connect.NewClient[v1.GetWeeklyAnalyticsRequest, v1.GetWeeklyAnalyticsResponse](
			httpClient,
			baseURL+AnalyticsServiceGetWeeklyAnalyticsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetWeeklyAnalytics")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analyticsServiceClient implements AnalyticsServiceClient.
type analyticsServiceClient struct {
	getProgressSummary *connect.Client[v1.GetProgressSummaryRequest, v1.GetProgressSummaryResponse]
	getWeeklyAnalytics *connect.Client[v1.GetWeeklyAnalyticsRequest, v1.GetWeeklyAnalyticsResponse]
}

// GetProgressSummary calls thanawy.v1.AnalyticsService.GetProgressSummary.
func (c *analyticsServiceClient) GetProgressSummary(ctx context.Context, req *connect.Request[v1.GetProgressSummaryRequest]) (*connect.Response[v1.GetProgressSummaryResponse], error) {
	return c.getProgressSummary.CallUnary(ctx, req)
}

// GetWeeklyAnalytics calls thanawy.v1.AnalyticsService.GetWeeklyAnalytics.
func (c *analyticsServiceClient) GetWeeklyAnalytics(ctx context.Context, req *connect.Request[v1.GetWeeklyAnalyticsRequest]) (*connect.Response[v1.GetWeeklyAnalyticsResponse], error) {
	return c.getWeeklyAnalytics.CallUnary(ctx, req)
}

// AnalyticsServiceHandler is an implementation of the thanawy.v1.AnalyticsService service.
type AnalyticsServiceHandler interface {
	GetProgressSummary(context.Context, *connect.Request[v1.GetProgressSummaryRequest]) (*connect.Response[v1.GetProgressSummaryResponse], error)
	GetWeeklyAnalytics(context.Context, *connect.Request[v1.GetWeeklyAnalyticsRequest]) (*connect.Response[v1.GetWeeklyAnalyticsResponse], error)
}

// NewAnalyticsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalyticsServiceHandler(svc AnalyticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analyticsServiceMethods := v1.File_thanawy_v1_analytics_proto.Services().ByName("AnalyticsService").Methods()
	analyticsServiceGetProgressSummaryHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetProgressSummaryProcedure,
		svc.GetProgressSummary,
		connect.WithSchema(analyticsServiceMethods.ByName("GetProgressSummary")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetWeeklyAnalyticsHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetWeeklyAnalyticsProcedure,
		svc.GetWeeklyAnalytics,
		connect.WithSchema(analyticsServiceMethods.ByName("GetWeeklyAnalytics")),
		connect.WithHandlerOptions(opts...),
	)
	return "/thanawy.v1.AnalyticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalyticsServiceGetProgressSummaryProcedure:
			analyticsServiceGetProgressSummaryHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetWeeklyAnalyticsProcedure:
			analyticsServiceGetWeeklyAnalyticsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalyticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalyticsServiceHandler struct{}

func (UnimplementedAnalyticsServiceHandler) GetProgressSummary(context.Context, *connect.Request[v1.GetProgressSummaryRequest]) (*connect.Response[v1.GetProgressSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.AnalyticsService.GetProgressSummary is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetWeeklyAnalytics(context.Context, *connect.Request[v1.GetWeeklyAnalyticsRequest]) (*connect.Response[v1.GetWeeklyAnalyticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.AnalyticsService.GetWeeklyAnalytics is not implemented"))
}
