// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: thanawy/v1/course.proto

package thanawyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "thanawy-backend/internal/proto/thanawy/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CourseServiceName is the fully-qualified name of the CourseService service.
	CourseServiceName = "thanawy.v1.CourseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CourseServiceCreateCourseProcedure is the fully-qualified name of the CourseService's
	// CreateCourse RPC.
	CourseServiceCreateCourseProcedure = "/thanawy.v1.CourseService/CreateCourse"
	// CourseServiceGetCourseProcedure is the fully-qualified name of the CourseService's GetCourse RPC.
	CourseServiceGetCourseProcedure = "/thanawy.v1.CourseService/GetCourse"
	// CourseServiceUpdateCourseProcedure is the fully-qualified name of the CourseService's
	// UpdateCourse RPC.
	CourseServiceUpdateCourseProcedure = "/thanawy.v1.CourseService/UpdateCourse"
	// CourseServiceDeleteCourseProcedure is the fully-qualified name of the CourseService's
	// DeleteCourse RPC.
	CourseServiceDeleteCourseProcedure = "/thanawy.v1.CourseService/DeleteCourse"
	// CourseServiceListCoursesProcedure is the fully-qualified name of the CourseService's ListCourses
	// RPC.
	CourseServiceListCoursesProcedure = "/thanawy.v1.CourseService/ListCourses"
	// CourseServiceSubmitForReviewProcedure is the fully-qualified name of the CourseService's
	// SubmitForReview RPC.
	CourseServiceSubmitForReviewProcedure = "/thanawy.v1.CourseService/SubmitForReview"
	// CourseServiceApproveCourseProcedure is the fully-qualified name of the CourseService's
	// ApproveCourse RPC.
	CourseServiceApproveCourseProcedure = "/thanawy.v1.CourseService/ApproveCourse"
	// CourseServiceRejectCourseProcedure is the fully-qualified name of the CourseService's
	// RejectCourse RPC.
	CourseServiceRejectCourseProcedure = "/thanawy.v1.CourseService/RejectCourse"
	// CourseServiceArchiveCourseProcedure is the fully-qualified name of the CourseService's
	// ArchiveCourse RPC.
	CourseServiceArchiveCourseProcedure = "/thanawy.v1.CourseService/ArchiveCourse"
	// CourseServiceUnarchiveCourseProcedure is the fully-qualified name of the CourseService's
	// UnarchiveCourse RPC.
	CourseServiceUnarchiveCourseProcedure = "/thanawy.v1.CourseService/UnarchiveCourse"
	// CourseServiceCreateSectionProcedure is the fully-qualified name of the CourseService's
	// CreateSection RPC.
	CourseServiceCreateSectionProcedure = "/thanawy.v1.CourseService/CreateSection"
	// CourseServiceUpdateSectionProcedure is the fully-qualified name of the CourseService's
	// UpdateSection RPC.
	CourseServiceUpdateSectionProcedure = "/thanawy.v1.CourseService/UpdateSection"
	// CourseServiceDeleteSectionProcedure is the fully-qualified name of the CourseService's
	// DeleteSection RPC.
	CourseServiceDeleteSectionProcedure = "/thanawy.v1.CourseService/DeleteSection"
	// CourseServiceListSectionsProcedure is the fully-qualified name of the CourseService's
	// ListSections RPC.
	CourseServiceListSectionsProcedure = "/thanawy.v1.CourseService/ListSections"
	// CourseServiceReorderSectionsProcedure is the fully-qualified name of the CourseService's
	// ReorderSections RPC.
	CourseServiceReorderSectionsProcedure = "/thanawy.v1.CourseService/ReorderSections"
	// CourseServiceCreateLessonProcedure is the fully-qualified name of the CourseService's
	// CreateLesson RPC.
	CourseServiceCreateLessonProcedure = "/thanawy.v1.CourseService/CreateLesson"
	// CourseServiceUpdateLessonProcedure is the fully-qualified name of the CourseService's
	// UpdateLesson RPC.
	CourseServiceUpdateLessonProcedure = "/thanawy.v1.CourseService/UpdateLesson"
	// CourseServiceDeleteLessonProcedure is the fully-qualified name of the CourseService's
	// DeleteLesson RPC.
	CourseServiceDeleteLessonProcedure = "/thanawy.v1.CourseService/DeleteLesson"
	// CourseServiceListLessonsProcedure is the fully-qualified name of the CourseService's ListLessons
	// RPC.
	CourseServiceListLessonsProcedure = "/thanawy.v1.CourseService/ListLessons"
	// CourseServiceReorderLessonsProcedure is the fully-qualified name of the CourseService's
	// ReorderLessons RPC.
	CourseServiceReorderLessonsProcedure = "/thanawy.v1.CourseService/ReorderLessons"
	// CourseServiceEnrollUserProcedure is the fully-qualified name of the CourseService's EnrollUser
	// RPC.
	CourseServiceEnrollUserProcedure = "/thanawy.v1.CourseService/EnrollUser"
	// CourseServiceGetEnrollmentProcedure is the fully-qualified name of the CourseService's
	// GetEnrollment RPC.
	CourseServiceGetEnrollmentProcedure = "/thanawy.v1.CourseService/GetEnrollment"
	// CourseServiceUpdateProgressProcedure is the fully-qualified name of the CourseService's
	// UpdateProgress RPC.
	CourseServiceUpdateProgressProcedure = "/thanawy.v1.CourseService/UpdateProgress"
	// CourseServiceListEnrollmentsProcedure is the fully-qualified name of the CourseService's
	// ListEnrollments RPC.
	CourseServiceListEnrollmentsProcedure = "/thanawy.v1.CourseService/ListEnrollments"
	// CourseServiceSetPricingProcedure is the fully-qualified name of the CourseService's SetPricing
	// RPC.
	CourseServiceSetPricingProcedure = "/thanawy.v1.CourseService/SetPricing"
	// CourseServiceGetPricingProcedure is the fully-qualified name of the CourseService's GetPricing
	// RPC.
	CourseServiceGetPricingProcedure = "/thanawy.v1.CourseService/GetPricing"
)

// CourseServiceClient is a client for the thanawy.v1.CourseService service.
type CourseServiceClient interface {
	// Course CRUD
	CreateCourse(context.Context, *connect.Request[v1.CreateCourseRequest]) (*connect.Response[v1.CreateCourseResponse], error)
	GetCourse(context.Context, *connect.Request[v1.GetCourseRequest]) (*connect.Response[v1.GetCourseResponse], error)
	UpdateCourse(context.Context, *connect.Request[v1.UpdateCourseRequest]) (*connect.Response[v1.UpdateCourseResponse], error)
	DeleteCourse(context.Context, *connect.Request[v1.DeleteCourseRequest]) (*connect.Response[v1.DeleteCourseResponse], error)
	ListCourses(context.Context, *connect.Request[v1.ListCoursesRequest]) (*connect.Response[v1.ListCoursesResponse], error)
	// Course Workflow
	SubmitForReview(context.Context, *connect.Request[v1.SubmitForReviewRequest]) (*connect.Response[v1.SubmitForReviewResponse], error)
	ApproveCourse(context.Context, *connect.Request[v1.ApproveCourseRequest]) (*connect.Response[v1.ApproveCourseResponse], error)
	RejectCourse(context.Context, *connect.Request[v1.RejectCourseRequest]) (*connect.Response[v1.RejectCourseResponse], error)
	ArchiveCourse(context.Context, *connect.Request[v1.ArchiveCourseRequest]) (*connect.Response[v1.ArchiveCourseResponse], error)
	UnarchiveCourse(context.Context, *connect.Request[v1.UnarchiveCourseRequest]) (*connect.Response[v1.UnarchiveCourseResponse], error)
	// Section Management
	CreateSection(context.Context, *connect.Request[v1.CreateSectionRequest]) (*connect.Response[v1.CreateSectionResponse], error)
	UpdateSection(context.Context, *connect.Request[v1.UpdateSectionRequest]) (*connect.Response[v1.UpdateSectionResponse], error)
	DeleteSection(context.Context, *connect.Request[v1.DeleteSectionRequest]) (*connect.Response[v1.DeleteSectionResponse], error)
	ListSections(context.Context, *connect.Request[v1.ListSectionsRequest]) (*connect.Response[v1.ListSectionsResponse], error)
	ReorderSections(context.Context, *connect.Request[v1.ReorderSectionsRequest]) (*connect.Response[v1.ReorderSectionsResponse], error)
	// Lesson Management
	CreateLesson(context.Context, *connect.Request[v1.CreateLessonRequest]) (*connect.Response[v1.CreateLessonResponse], error)
	UpdateLesson(context.Context, *connect.Request[v1.UpdateLessonRequest]) (*connect.Response[v1.UpdateLessonResponse], error)
	DeleteLesson(context.Context, *connect.Request[v1.DeleteLessonRequest]) (*connect.Response[v1.DeleteLessonResponse], error)
	ListLessons(context.Context, *connect.Request[v1.ListLessonsRequest]) (*connect.Response[v1.ListLessonsResponse], error)
	ReorderLessons(context.Context, *connect.Request[v1.ReorderLessonsRequest]) (*connect.Response[v1.ReorderLessonsResponse], error)
	// Enrollment Management
	EnrollUser(context.Context, *connect.Request[v1.EnrollUserRequest]) (*connect.Response[v1.EnrollUserResponse], error)
	GetEnrollment(context.Context, *connect.Request[v1.GetEnrollmentRequest]) (*connect.Response[v1.GetEnrollmentResponse], error)
	UpdateProgress(context.Context, *connect.Request[v1.UpdateProgressRequest]) (*connect.Response[v1.UpdateProgressResponse], error)
	ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error)
	// Pricing Management
	SetPricing(context.Context, *connect.Request[v1.SetPricingRequest]) (*connect.Response[v1.SetPricingResponse], error)
	GetPricing(context.Context, *connect.Request[v1.GetPricingRequest]) (*connect.Response[v1.GetPricingResponse], error)
}

// NewCourseServiceClient constructs a client for the thanawy.v1.CourseService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCourseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CourseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	courseServiceMethods := v1.File_thanawy_v1_course_proto.Services().ByName("CourseService").Methods()
	return &courseServiceClient{
		createCourse: connect.NewClient[v1.CreateCourseRequest, v1.CreateCourseResponse](
			httpClient,
			baseURL+CourseServiceCreateCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("CreateCourse")),
			connect.WithClientOptions(opts...),
		),
		getCourse: connect.NewClient[v1.GetCourseRequest, v1.GetCourseResponse](
			httpClient,
			baseURL+CourseServiceGetCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("GetCourse")),
			connect.WithClientOptions(opts...),
		),
		updateCourse: connect.NewClient[v1.UpdateCourseRequest, v1.UpdateCourseResponse](
			httpClient,
			baseURL+CourseServiceUpdateCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("UpdateCourse")),
			connect.WithClientOptions(opts...),
		),
		deleteCourse: connect.NewClient[v1.DeleteCourseRequest, v1.DeleteCourseResponse](
			httpClient,
			baseURL+CourseServiceDeleteCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("DeleteCourse")),
			connect.WithClientOptions(opts...),
		),
		listCourses: connect.NewClient[v1.ListCoursesRequest, v1.ListCoursesResponse](
			httpClient,
			baseURL+CourseServiceListCoursesProcedure,
			connect.WithSchema(courseServiceMethods.ByName("ListCourses")),
			connect.WithClientOptions(opts...),
		),
		submitForReview: connect.NewClient[v1.SubmitForReviewRequest, v1.SubmitForReviewResponse](
			httpClient,
			baseURL+CourseServiceSubmitForReviewProcedure,
			connect.WithSchema(courseServiceMethods.ByName("SubmitForReview")),
			connect.WithClientOptions(opts...),
		),
		approveCourse: connect.NewClient[v1.ApproveCourseRequest, v1.ApproveCourseResponse](
			httpClient,
			baseURL+CourseServiceApproveCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("ApproveCourse")),
			connect.WithClientOptions(opts...),
		),
		rejectCourse: connect.NewClient[v1.RejectCourseRequest, v1.RejectCourseResponse](
			httpClient,
			baseURL+CourseServiceRejectCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("RejectCourse")),
			connect.WithClientOptions(opts...),
		),
		archiveCourse: connect.NewClient[v1.ArchiveCourseRequest, v1.ArchiveCourseResponse](
			httpClient,
			baseURL+CourseServiceArchiveCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("ArchiveCourse")),
			connect.WithClientOptions(opts...),
		),
		unarchiveCourse: connect.NewClient[v1.UnarchiveCourseRequest, v1.UnarchiveCourseResponse](
			httpClient,
			baseURL+CourseServiceUnarchiveCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("UnarchiveCourse")),
			connect.WithClientOptions(opts...),
		),
		createSection: connect.NewClient[v1.CreateSectionRequest, v1.CreateSectionResponse](
			httpClient,
			baseURL+CourseServiceCreateSectionProcedure,
			connect.WithSchema(courseServiceMethods.ByName("CreateSection")),
			connect.WithClientOptions(opts...),
		),
		updateSection: connect.NewClient[v1.UpdateSectionRequest, v1.UpdateSectionResponse](
			httpClient,
			baseURL+CourseServiceUpdateSectionProcedure,
			connect.WithSchema(courseServiceMethods.ByName("UpdateSection")),
			connect.WithClientOptions(opts...),
		),
		deleteSection: connect.NewClient[v1.DeleteSectionRequest, v1.DeleteSectionResponse](
			httpClient,
			baseURL+CourseServiceDeleteSectionProcedure,
			connect.WithSchema(courseServiceMethods.ByName("DeleteSection")),
			connect.WithClientOptions(opts...),
		),
		listSections: connect.NewClient[v1.ListSectionsRequest, v1.ListSectionsResponse](
			httpClient,
			baseURL+CourseServiceListSectionsProcedure,
			connect.WithSchema(courseServiceMethods.ByName("ListSections")),
			connect.WithClientOptions(opts...),
		),
		reorderSections: connect.NewClient[v1.ReorderSectionsRequest, v1.ReorderSectionsResponse](
			httpClient,
			baseURL+CourseServiceReorderSectionsProcedure,
			connect.WithSchema(courseServiceMethods.ByName("ReorderSections")),
			connect.WithClientOptions(opts...),
		),
		createLesson: connect.NewClient[v1.CreateLessonRequest, v1.CreateLessonResponse](
			httpClient,
			baseURL+CourseServiceCreateLessonProcedure,
			connect.WithSchema(courseServiceMethods.ByName("CreateLesson")),
			connect.WithClientOptions(opts...),
		),
		updateLesson: connect.NewClient[v1.UpdateLessonRequest, v1.UpdateLessonResponse](
			httpClient,
			baseURL+CourseServiceUpdateLessonProcedure,
			connect.WithSchema(courseServiceMethods.ByName("UpdateLesson")),
			connect.WithClientOptions(opts...),
		),
		deleteLesson: connect.NewClient[v1.DeleteLessonRequest, v1.DeleteLessonResponse](
			httpClient,
			baseURL+CourseServiceDeleteLessonProcedure,
			connect.WithSchema(courseServiceMethods.ByName("DeleteLesson")),
			connect.WithClientOptions(opts...),
		),
		listLessons: connect.NewClient[v1.ListLessonsRequest, v1.ListLessonsResponse](
			httpClient,
			baseURL+CourseServiceListLessonsProcedure,
			connect.WithSchema(courseServiceMethods.ByName("ListLessons")),
			connect.WithClientOptions(opts...),
		),
		reorderLessons: connect.NewClient[v1.ReorderLessonsRequest, v1.ReorderLessonsResponse](
			httpClient,
			baseURL+CourseServiceReorderLessonsProcedure,
			connect.WithSchema(courseServiceMethods.ByName("ReorderLessons")),
			connect.WithClientOptions(opts...),
		),
		enrollUser: connect.NewClient[v1.EnrollUserRequest, v1.EnrollUserResponse](
			httpClient,
			baseURL+CourseServiceEnrollUserProcedure,
			connect.WithSchema(courseServiceMethods.ByName("EnrollUser")),
			connect.WithClientOptions(opts...),
		),
		getEnrollment: connect.NewClient[v1.GetEnrollmentRequest, v1.GetEnrollmentResponse](
			httpClient,
			baseURL+CourseServiceGetEnrollmentProcedure,
			connect.WithSchema(courseServiceMethods.ByName("GetEnrollment")),
			connect.WithClientOptions(opts...),
		),
		updateProgress: connect.NewClient[v1.UpdateProgressRequest, v1.UpdateProgressResponse](
			httpClient,
			baseURL+CourseServiceUpdateProgressProcedure,
			connect.WithSchema(courseServiceMethods.ByName("UpdateProgress")),
			connect.WithClientOptions(opts...),
		),
		listEnrollments: connect.NewClient[v1.ListEnrollmentsRequest, v1.ListEnrollmentsResponse](
			httpClient,
			baseURL+CourseServiceListEnrollmentsProcedure,
			connect.WithSchema(courseServiceMethods.ByName("ListEnrollments")),
			connect.WithClientOptions(opts...),
		),
		setPricing: connect.NewClient[v1.SetPricingRequest, v1.SetPricingResponse](
			httpClient,
			baseURL+CourseServiceSetPricingProcedure,
			connect.WithSchema(courseServiceMethods.ByName("SetPricing")),
			connect.WithClientOptions(opts...),
		),
		getPricing: connect.NewClient[v1.GetPricingRequest, v1.GetPricingResponse](
			httpClient,
			baseURL+CourseServiceGetPricingProcedure,
			connect.WithSchema(courseServiceMethods.ByName("GetPricing")),
			connect.WithClientOptions(opts...),
		),
	}
}

// courseServiceClient implements CourseServiceClient.
type courseServiceClient struct {
	createCourse    *connect.Client[v1.CreateCourseRequest, v1.CreateCourseResponse]
	getCourse       *connect.Client[v1.GetCourseRequest, v1.GetCourseResponse]
	updateCourse    *connect.Client[v1.UpdateCourseRequest, v1.UpdateCourseResponse]
	deleteCourse    *connect.Client[v1.DeleteCourseRequest, v1.DeleteCourseResponse]
	listCourses     *connect.Client[v1.ListCoursesRequest, v1.ListCoursesResponse]
	submitForReview *connect.Client[v1.SubmitForReviewRequest, v1.SubmitForReviewResponse]
	approveCourse   *connect.Client[v1.ApproveCourseRequest, v1.ApproveCourseResponse]
	rejectCourse    *connect.Client[v1.RejectCourseRequest, v1.RejectCourseResponse]
	archiveCourse   *connect.Client[v1.ArchiveCourseRequest, v1.ArchiveCourseResponse]
	unarchiveCourse *connect.Client[v1.UnarchiveCourseRequest, v1.UnarchiveCourseResponse]
	createSection   *connect.Client[v1.CreateSectionRequest, v1.CreateSectionResponse]
	updateSection   *connect.Client[v1.UpdateSectionRequest, v1.UpdateSectionResponse]
	deleteSection   *connect.Client[v1.DeleteSectionRequest, v1.DeleteSectionResponse]
	listSections    *connect.Client[v1.ListSectionsRequest, v1.ListSectionsResponse]
	reorderSections *connect.Client[v1.ReorderSectionsRequest, v1.ReorderSectionsResponse]
	createLesson    *connect.Client[v1.CreateLessonRequest, v1.CreateLessonResponse]
	updateLesson    *connect.Client[v1.UpdateLessonRequest, v1.UpdateLessonResponse]
	deleteLesson    *connect.Client[v1.DeleteLessonRequest, v1.DeleteLessonResponse]
	listLessons     *connect.Client[v1.ListLessonsRequest, v1.ListLessonsResponse]
	reorderLessons  *connect.Client[v1.ReorderLessonsRequest, v1.ReorderLessonsResponse]
	enrollUser      *connect.Client[v1.EnrollUserRequest, v1.EnrollUserResponse]
	getEnrollment   *connect.Client[v1.GetEnrollmentRequest, v1.GetEnrollmentResponse]
	updateProgress  *connect.Client[v1.UpdateProgressRequest, v1.UpdateProgressResponse]
	listEnrollments *connect.Client[v1.ListEnrollmentsRequest, v1.ListEnrollmentsResponse]
	setPricing      *connect.Client[v1.SetPricingRequest, v1.SetPricingResponse]
	getPricing      *connect.Client[v1.GetPricingRequest, v1.GetPricingResponse]
}

// CreateCourse calls thanawy.v1.CourseService.CreateCourse.
func (c *courseServiceClient) CreateCourse(ctx context.Context, req *connect.Request[v1.CreateCourseRequest]) (*connect.Response[v1.CreateCourseResponse], error) {
	return c.createCourse.CallUnary(ctx, req)
}

// GetCourse calls thanawy.v1.CourseService.GetCourse.
func (c *courseServiceClient) GetCourse(ctx context.Context, req *connect.Request[v1.GetCourseRequest]) (*connect.Response[v1.GetCourseResponse], error) {
	return c.getCourse.CallUnary(ctx, req)
}

// UpdateCourse calls thanawy.v1.CourseService.UpdateCourse.
func (c *courseServiceClient) UpdateCourse(ctx context.Context, req *connect.Request[v1.UpdateCourseRequest]) (*connect.Response[v1.UpdateCourseResponse], error) {
	return c.updateCourse.CallUnary(ctx, req)
}

// DeleteCourse calls thanawy.v1.CourseService.DeleteCourse.
func (c *courseServiceClient) DeleteCourse(ctx context.Context, req *connect.Request[v1.DeleteCourseRequest]) (*connect.Response[v1.DeleteCourseResponse], error) {
	return c.deleteCourse.CallUnary(ctx, req)
}

// ListCourses calls thanawy.v1.CourseService.ListCourses.
func (c *courseServiceClient) ListCourses(ctx context.Context, req *connect.Request[v1.ListCoursesRequest]) (*connect.Response[v1.ListCoursesResponse], error) {
	return c.listCourses.CallUnary(ctx, req)
}

// SubmitForReview calls thanawy.v1.CourseService.SubmitForReview.
func (c *courseServiceClient) SubmitForReview(ctx context.Context, req *connect.Request[v1.SubmitForReviewRequest]) (*connect.Response[v1.SubmitForReviewResponse], error) {
	return c.submitForReview.CallUnary(ctx, req)
}

// ApproveCourse calls thanawy.v1.CourseService.ApproveCourse.
func (c *courseServiceClient) ApproveCourse(ctx context.Context, req *connect.Request[v1.ApproveCourseRequest]) (*connect.Response[v1.ApproveCourseResponse], error) {
	return c.approveCourse.CallUnary(ctx, req)
}

// RejectCourse calls thanawy.v1.CourseService.RejectCourse.
func (c *courseServiceClient) RejectCourse(ctx context.Context, req *connect.Request[v1.RejectCourseRequest]) (*connect.Response[v1.RejectCourseResponse], error) {
	return c.rejectCourse.CallUnary(ctx, req)
}

// ArchiveCourse calls thanawy.v1.CourseService.ArchiveCourse.
func (c *courseServiceClient) ArchiveCourse(ctx context.Context, req *connect.Request[v1.ArchiveCourseRequest]) (*connect.Response[v1.ArchiveCourseResponse], error) {
	return c.archiveCourse.CallUnary(ctx, req)
}

// UnarchiveCourse calls thanawy.v1.CourseService.UnarchiveCourse.
func (c *courseServiceClient) UnarchiveCourse(ctx context.Context, req *connect.Request[v1.UnarchiveCourseRequest]) (*connect.Response[v1.UnarchiveCourseResponse], error) {
	return c.unarchiveCourse.CallUnary(ctx, req)
}

// CreateSection calls thanawy.v1.CourseService.CreateSection.
func (c *courseServiceClient) CreateSection(ctx context.Context, req *connect.Request[v1.CreateSectionRequest]) (*connect.Response[v1.CreateSectionResponse], error) {
	return c.createSection.CallUnary(ctx, req)
}

// UpdateSection calls thanawy.v1.CourseService.UpdateSection.
func (c *courseServiceClient) UpdateSection(ctx context.Context, req *connect.Request[v1.UpdateSectionRequest]) (*connect.Response[v1.UpdateSectionResponse], error) {
	return c.updateSection.CallUnary(ctx, req)
}

// DeleteSection calls thanawy.v1.CourseService.DeleteSection.
func (c *courseServiceClient) DeleteSection(ctx context.Context, req *connect.Request[v1.DeleteSectionRequest]) (*connect.Response[v1.DeleteSectionResponse], error) {
	return c.deleteSection.CallUnary(ctx, req)
}

// ListSections calls thanawy.v1.CourseService.ListSections.
func (c *courseServiceClient) ListSections(ctx context.Context, req *connect.Request[v1.ListSectionsRequest]) (*connect.Response[v1.ListSectionsResponse], error) {
	return c.listSections.CallUnary(ctx, req)
}

// ReorderSections calls thanawy.v1.CourseService.ReorderSections.
func (c *courseServiceClient) ReorderSections(ctx context.Context, req *connect.Request[v1.ReorderSectionsRequest]) (*connect.Response[v1.ReorderSectionsResponse], error) {
	return c.reorderSections.CallUnary(ctx, req)
}

// CreateLesson calls thanawy.v1.CourseService.CreateLesson.
func (c *courseServiceClient) CreateLesson(ctx context.Context, req *connect.Request[v1.CreateLessonRequest]) (*connect.Response[v1.CreateLessonResponse], error) {
	return c.createLesson.CallUnary(ctx, req)
}

// UpdateLesson calls thanawy.v1.CourseService.UpdateLesson.
func (c *courseServiceClient) UpdateLesson(ctx context.Context, req *connect.Request[v1.UpdateLessonRequest]) (*connect.Response[v1.UpdateLessonResponse], error) {
	return c.updateLesson.CallUnary(ctx, req)
}

// DeleteLesson calls thanawy.v1.CourseService.DeleteLesson.
func (c *courseServiceClient) DeleteLesson(ctx context.Context, req *connect.Request[v1.DeleteLessonRequest]) (*connect.Response[v1.DeleteLessonResponse], error) {
	return c.deleteLesson.CallUnary(ctx, req)
}

// ListLessons calls thanawy.v1.CourseService.ListLessons.
func (c *courseServiceClient) ListLessons(ctx context.Context, req *connect.Request[v1.ListLessonsRequest]) (*connect.Response[v1.ListLessonsResponse], error) {
	return c.listLessons.CallUnary(ctx, req)
}

// ReorderLessons calls thanawy.v1.CourseService.ReorderLessons.
func (c *courseServiceClient) ReorderLessons(ctx context.Context, req *connect.Request[v1.ReorderLessonsRequest]) (*connect.Response[v1.ReorderLessonsResponse], error) {
	return c.reorderLessons.CallUnary(ctx, req)
}

// EnrollUser calls thanawy.v1.CourseService.EnrollUser.
func (c *courseServiceClient) EnrollUser(ctx context.Context, req *connect.Request[v1.EnrollUserRequest]) (*connect.Response[v1.EnrollUserResponse], error) {
	return c.enrollUser.CallUnary(ctx, req)
}

// GetEnrollment calls thanawy.v1.CourseService.GetEnrollment.
func (c *courseServiceClient) GetEnrollment(ctx context.Context, req *connect.Request[v1.GetEnrollmentRequest]) (*connect.Response[v1.GetEnrollmentResponse], error) {
	return c.getEnrollment.CallUnary(ctx, req)
}

// UpdateProgress calls thanawy.v1.CourseService.UpdateProgress.
func (c *courseServiceClient) UpdateProgress(ctx context.Context, req *connect.Request[v1.UpdateProgressRequest]) (*connect.Response[v1.UpdateProgressResponse], error) {
	return c.updateProgress.CallUnary(ctx, req)
}

// ListEnrollments calls thanawy.v1.CourseService.ListEnrollments.
func (c *courseServiceClient) ListEnrollments(ctx context.Context, req *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error) {
	return c.listEnrollments.CallUnary(ctx, req)
}

// SetPricing calls thanawy.v1.CourseService.SetPricing.
func (c *courseServiceClient) SetPricing(ctx context.Context, req *connect.Request[v1.SetPricingRequest]) (*connect.Response[v1.SetPricingResponse], error) {
	return c.setPricing.CallUnary(ctx, req)
}

// GetPricing calls thanawy.v1.CourseService.GetPricing.
func (c *courseServiceClient) GetPricing(ctx context.Context, req *connect.Request[v1.GetPricingRequest]) (*connect.Response[v1.GetPricingResponse], error) {
	return c.getPricing.CallUnary(ctx, req)
}

// CourseServiceHandler is an implementation of the thanawy.v1.CourseService service.
type CourseServiceHandler interface {
	// Course CRUD
	CreateCourse(context.Context, *connect.Request[v1.CreateCourseRequest]) (*connect.Response[v1.CreateCourseResponse], error)
	GetCourse(context.Context, *connect.Request[v1.GetCourseRequest]) (*connect.Response[v1.GetCourseResponse], error)
	UpdateCourse(context.Context, *connect.Request[v1.UpdateCourseRequest]) (*connect.Response[v1.UpdateCourseResponse], error)
	DeleteCourse(context.Context, *connect.Request[v1.DeleteCourseRequest]) (*connect.Response[v1.DeleteCourseResponse], error)
	ListCourses(context.Context, *connect.Request[v1.ListCoursesRequest]) (*connect.Response[v1.ListCoursesResponse], error)
	// Course Workflow
	SubmitForReview(context.Context, *connect.Request[v1.SubmitForReviewRequest]) (*connect.Response[v1.SubmitForReviewResponse], error)
	ApproveCourse(context.Context, *connect.Request[v1.ApproveCourseRequest]) (*connect.Response[v1.ApproveCourseResponse], error)
	RejectCourse(context.Context, *connect.Request[v1.RejectCourseRequest]) (*connect.Response[v1.RejectCourseResponse], error)
	ArchiveCourse(context.Context, *connect.Request[v1.ArchiveCourseRequest]) (*connect.Response[v1.ArchiveCourseResponse], error)
	UnarchiveCourse(context.Context, *connect.Request[v1.UnarchiveCourseRequest]) (*connect.Response[v1.UnarchiveCourseResponse], error)
	// Section Management
	CreateSection(context.Context, *connect.Request[v1.CreateSectionRequest]) (*connect.Response[v1.CreateSectionResponse], error)
	UpdateSection(context.Context, *connect.Request[v1.UpdateSectionRequest]) (*connect.Response[v1.UpdateSectionResponse], error)
	DeleteSection(context.Context, *connect.Request[v1.DeleteSectionRequest]) (*connect.Response[v1.DeleteSectionResponse], error)
	ListSections(context.Context, *connect.Request[v1.ListSectionsRequest]) (*connect.Response[v1.ListSectionsResponse], error)
	ReorderSections(context.Context, *connect.Request[v1.ReorderSectionsRequest]) (*connect.Response[v1.ReorderSectionsResponse], error)
	// Lesson Management
	CreateLesson(context.Context, *connect.Request[v1.CreateLessonRequest]) (*connect.Response[v1.CreateLessonResponse], error)
	UpdateLesson(context.Context, *connect.Request[v1.UpdateLessonRequest]) (*connect.Response[v1.UpdateLessonResponse], error)
	DeleteLesson(context.Context, *connect.Request[v1.DeleteLessonRequest]) (*connect.Response[v1.DeleteLessonResponse], error)
	ListLessons(context.Context, *connect.Request[v1.ListLessonsRequest]) (*connect.Response[v1.ListLessonsResponse], error)
	ReorderLessons(context.Context, *connect.Request[v1.ReorderLessonsRequest]) (*connect.Response[v1.ReorderLessonsResponse], error)
	// Enrollment Management
	EnrollUser(context.Context, *connect.Request[v1.EnrollUserRequest]) (*connect.Response[v1.EnrollUserResponse], error)
	GetEnrollment(context.Context, *connect.Request[v1.GetEnrollmentRequest]) (*connect.Response[v1.GetEnrollmentResponse], error)
	UpdateProgress(context.Context, *connect.Request[v1.UpdateProgressRequest]) (*connect.Response[v1.UpdateProgressResponse], error)
	ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error)
	// Pricing Management
	SetPricing(context.Context, *connect.Request[v1.SetPricingRequest]) (*connect.Response[v1.SetPricingResponse], error)
	GetPricing(context.Context, *connect.Request[v1.GetPricingRequest]) (*connect.Response[v1.GetPricingResponse], error)
}

// NewCourseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCourseServiceHandler(svc CourseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	courseServiceMethods := v1.File_thanawy_v1_course_proto.Services().ByName("CourseService").Methods()
	courseServiceCreateCourseHandler := connect.NewUnaryHandler(
		CourseServiceCreateCourseProcedure,
		svc.CreateCourse,
		connect.WithSchema(courseServiceMethods.ByName("CreateCourse")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceGetCourseHandler := connect.NewUnaryHandler(
		CourseServiceGetCourseProcedure,
		svc.GetCourse,
		connect.WithSchema(courseServiceMethods.ByName("GetCourse")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceUpdateCourseHandler := connect.NewUnaryHandler(
		CourseServiceUpdateCourseProcedure,
		svc.UpdateCourse,
		connect.WithSchema(courseServiceMethods.ByName("UpdateCourse")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceDeleteCourseHandler := connect.NewUnaryHandler(
		CourseServiceDeleteCourseProcedure,
		svc.DeleteCourse,
		connect.WithSchema(courseServiceMethods.ByName("DeleteCourse")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceListCoursesHandler := connect.NewUnaryHandler(
		CourseServiceListCoursesProcedure,
		svc.ListCourses,
		connect.WithSchema(courseServiceMethods.ByName("ListCourses")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceSubmitForReviewHandler := connect.NewUnaryHandler(
		CourseServiceSubmitForReviewProcedure,
		svc.SubmitForReview,
		connect.WithSchema(courseServiceMethods.ByName("SubmitForReview")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceApproveCourseHandler := connect.NewUnaryHandler(
		CourseServiceApproveCourseProcedure,
		svc.ApproveCourse,
		connect.WithSchema(courseServiceMethods.ByName("ApproveCourse")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceRejectCourseHandler := connect.NewUnaryHandler(
		CourseServiceRejectCourseProcedure,
		svc.RejectCourse,
		connect.WithSchema(courseServiceMethods.ByName("RejectCourse")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceArchiveCourseHandler := connect.NewUnaryHandler(
		CourseServiceArchiveCourseProcedure,
		svc.ArchiveCourse,
		connect.WithSchema(courseServiceMethods.ByName("ArchiveCourse")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceUnarchiveCourseHandler := connect.NewUnaryHandler(
		CourseServiceUnarchiveCourseProcedure,
		svc.UnarchiveCourse,
		connect.WithSchema(courseServiceMethods.ByName("UnarchiveCourse")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceCreateSectionHandler := connect.NewUnaryHandler(
		CourseServiceCreateSectionProcedure,
		svc.CreateSection,
		connect.WithSchema(courseServiceMethods.ByName("CreateSection")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceUpdateSectionHandler := connect.NewUnaryHandler(
		CourseServiceUpdateSectionProcedure,
		svc.UpdateSection,
		connect.WithSchema(courseServiceMethods.ByName("UpdateSection")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceDeleteSectionHandler := connect.NewUnaryHandler(
		CourseServiceDeleteSectionProcedure,
		svc.DeleteSection,
		connect.WithSchema(courseServiceMethods.ByName("DeleteSection")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceListSectionsHandler := connect.NewUnaryHandler(
		CourseServiceListSectionsProcedure,
		svc.ListSections,
		connect.WithSchema(courseServiceMethods.ByName("ListSections")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceReorderSectionsHandler := connect.NewUnaryHandler(
		CourseServiceReorderSectionsProcedure,
		svc.ReorderSections,
		connect.WithSchema(courseServiceMethods.ByName("ReorderSections")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceCreateLessonHandler := connect.NewUnaryHandler(
		CourseServiceCreateLessonProcedure,
		svc.CreateLesson,
		connect.WithSchema(courseServiceMethods.ByName("CreateLesson")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceUpdateLessonHandler := connect.NewUnaryHandler(
		CourseServiceUpdateLessonProcedure,
		svc.UpdateLesson,
		connect.WithSchema(courseServiceMethods.ByName("UpdateLesson")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceDeleteLessonHandler := connect.NewUnaryHandler(
		CourseServiceDeleteLessonProcedure,
		svc.DeleteLesson,
		connect.WithSchema(courseServiceMethods.ByName("DeleteLesson")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceListLessonsHandler := connect.NewUnaryHandler(
		CourseServiceListLessonsProcedure,
		svc.ListLessons,
		connect.WithSchema(courseServiceMethods.ByName("ListLessons")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceReorderLessonsHandler := connect.NewUnaryHandler(
		CourseServiceReorderLessonsProcedure,
		svc.ReorderLessons,
		connect.WithSchema(courseServiceMethods.ByName("ReorderLessons")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceEnrollUserHandler := connect.NewUnaryHandler(
		CourseServiceEnrollUserProcedure,
		svc.EnrollUser,
		connect.WithSchema(courseServiceMethods.ByName("EnrollUser")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceGetEnrollmentHandler := connect.NewUnaryHandler(
		CourseServiceGetEnrollmentProcedure,
		svc.GetEnrollment,
		connect.WithSchema(courseServiceMethods.ByName("GetEnrollment")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceUpdateProgressHandler := connect.NewUnaryHandler(
		CourseServiceUpdateProgressProcedure,
		svc.UpdateProgress,
		connect.WithSchema(courseServiceMethods.ByName("UpdateProgress")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceListEnrollmentsHandler := connect.NewUnaryHandler(
		CourseServiceListEnrollmentsProcedure,
		svc.ListEnrollments,
		connect.WithSchema(courseServiceMethods.ByName("ListEnrollments")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceSetPricingHandler := connect.NewUnaryHandler(
		CourseServiceSetPricingProcedure,
		svc.SetPricing,
		connect.WithSchema(courseServiceMethods.ByName("SetPricing")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceGetPricingHandler := connect.NewUnaryHandler(
		CourseServiceGetPricingProcedure,
		svc.GetPricing,
		connect.WithSchema(courseServiceMethods.ByName("GetPricing")),
		connect.WithHandlerOptions(opts...),
	)
	return "/thanawy.v1.CourseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CourseServiceCreateCourseProcedure:
			courseServiceCreateCourseHandler.ServeHTTP(w, r)
		case CourseServiceGetCourseProcedure:
			courseServiceGetCourseHandler.ServeHTTP(w, r)
		case CourseServiceUpdateCourseProcedure:
			courseServiceUpdateCourseHandler.ServeHTTP(w, r)
		case CourseServiceDeleteCourseProcedure:
			courseServiceDeleteCourseHandler.ServeHTTP(w, r)
		case CourseServiceListCoursesProcedure:
			courseServiceListCoursesHandler.ServeHTTP(w, r)
		case CourseServiceSubmitForReviewProcedure:
			courseServiceSubmitForReviewHandler.ServeHTTP(w, r)
		case CourseServiceApproveCourseProcedure:
			courseServiceApproveCourseHandler.ServeHTTP(w, r)
		case CourseServiceRejectCourseProcedure:
			courseServiceRejectCourseHandler.ServeHTTP(w, r)
		case CourseServiceArchiveCourseProcedure:
			courseServiceArchiveCourseHandler.ServeHTTP(w, r)
		case CourseServiceUnarchiveCourseProcedure:
			courseServiceUnarchiveCourseHandler.ServeHTTP(w, r)
		case CourseServiceCreateSectionProcedure:
			courseServiceCreateSectionHandler.ServeHTTP(w, r)
		case CourseServiceUpdateSectionProcedure:
			courseServiceUpdateSectionHandler.ServeHTTP(w, r)
		case CourseServiceDeleteSectionProcedure:
			courseServiceDeleteSectionHandler.ServeHTTP(w, r)
		case CourseServiceListSectionsProcedure:
			courseServiceListSectionsHandler.ServeHTTP(w, r)
		case CourseServiceReorderSectionsProcedure:
			courseServiceReorderSectionsHandler.ServeHTTP(w, r)
		case CourseServiceCreateLessonProcedure:
			courseServiceCreateLessonHandler.ServeHTTP(w, r)
		case CourseServiceUpdateLessonProcedure:
			courseServiceUpdateLessonHandler.ServeHTTP(w, r)
		case CourseServiceDeleteLessonProcedure:
			courseServiceDeleteLessonHandler.ServeHTTP(w, r)
		case CourseServiceListLessonsProcedure:
			courseServiceListLessonsHandler.ServeHTTP(w, r)
		case CourseServiceReorderLessonsProcedure:
			courseServiceReorderLessonsHandler.ServeHTTP(w, r)
		case CourseServiceEnrollUserProcedure:
			courseServiceEnrollUserHandler.ServeHTTP(w, r)
		case CourseServiceGetEnrollmentProcedure:
			courseServiceGetEnrollmentHandler.ServeHTTP(w, r)
		case CourseServiceUpdateProgressProcedure:
			courseServiceUpdateProgressHandler.ServeHTTP(w, r)
		case CourseServiceListEnrollmentsProcedure:
			courseServiceListEnrollmentsHandler.ServeHTTP(w, r)
		case CourseServiceSetPricingProcedure:
			courseServiceSetPricingHandler.ServeHTTP(w, r)
		case CourseServiceGetPricingProcedure:
			courseServiceGetPricingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCourseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCourseServiceHandler struct{}

func (UnimplementedCourseServiceHandler) CreateCourse(context.Context, *connect.Request[v1.CreateCourseRequest]) (*connect.Response[v1.CreateCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.CreateCourse is not implemented"))
}

func (UnimplementedCourseServiceHandler) GetCourse(context.Context, *connect.Request[v1.GetCourseRequest]) (*connect.Response[v1.GetCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.GetCourse is not implemented"))
}

func (UnimplementedCourseServiceHandler) UpdateCourse(context.Context, *connect.Request[v1.UpdateCourseRequest]) (*connect.Response[v1.UpdateCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.UpdateCourse is not implemented"))
}

func (UnimplementedCourseServiceHandler) DeleteCourse(context.Context, *connect.Request[v1.DeleteCourseRequest]) (*connect.Response[v1.DeleteCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.DeleteCourse is not implemented"))
}

func (UnimplementedCourseServiceHandler) ListCourses(context.Context, *connect.Request[v1.ListCoursesRequest]) (*connect.Response[v1.ListCoursesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.ListCourses is not implemented"))
}

func (UnimplementedCourseServiceHandler) SubmitForReview(context.Context, *connect.Request[v1.SubmitForReviewRequest]) (*connect.Response[v1.SubmitForReviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.SubmitForReview is not implemented"))
}

func (UnimplementedCourseServiceHandler) ApproveCourse(context.Context, *connect.Request[v1.ApproveCourseRequest]) (*connect.Response[v1.ApproveCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.ApproveCourse is not implemented"))
}

func (UnimplementedCourseServiceHandler) RejectCourse(context.Context, *connect.Request[v1.RejectCourseRequest]) (*connect.Response[v1.RejectCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.RejectCourse is not implemented"))
}

func (UnimplementedCourseServiceHandler) ArchiveCourse(context.Context, *connect.Request[v1.ArchiveCourseRequest]) (*connect.Response[v1.ArchiveCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.ArchiveCourse is not implemented"))
}

func (UnimplementedCourseServiceHandler) UnarchiveCourse(context.Context, *connect.Request[v1.UnarchiveCourseRequest]) (*connect.Response[v1.UnarchiveCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.UnarchiveCourse is not implemented"))
}

func (UnimplementedCourseServiceHandler) CreateSection(context.Context, *connect.Request[v1.CreateSectionRequest]) (*connect.Response[v1.CreateSectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.CreateSection is not implemented"))
}

func (UnimplementedCourseServiceHandler) UpdateSection(context.Context, *connect.Request[v1.UpdateSectionRequest]) (*connect.Response[v1.UpdateSectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.UpdateSection is not implemented"))
}

func (UnimplementedCourseServiceHandler) DeleteSection(context.Context, *connect.Request[v1.DeleteSectionRequest]) (*connect.Response[v1.DeleteSectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.DeleteSection is not implemented"))
}

func (UnimplementedCourseServiceHandler) ListSections(context.Context, *connect.Request[v1.ListSectionsRequest]) (*connect.Response[v1.ListSectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.ListSections is not implemented"))
}

func (UnimplementedCourseServiceHandler) ReorderSections(context.Context, *connect.Request[v1.ReorderSectionsRequest]) (*connect.Response[v1.ReorderSectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.ReorderSections is not implemented"))
}

func (UnimplementedCourseServiceHandler) CreateLesson(context.Context, *connect.Request[v1.CreateLessonRequest]) (*connect.Response[v1.CreateLessonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.CreateLesson is not implemented"))
}

func (UnimplementedCourseServiceHandler) UpdateLesson(context.Context, *connect.Request[v1.UpdateLessonRequest]) (*connect.Response[v1.UpdateLessonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.UpdateLesson is not implemented"))
}

func (UnimplementedCourseServiceHandler) DeleteLesson(context.Context, *connect.Request[v1.DeleteLessonRequest]) (*connect.Response[v1.DeleteLessonResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.DeleteLesson is not implemented"))
}

func (UnimplementedCourseServiceHandler) ListLessons(context.Context, *connect.Request[v1.ListLessonsRequest]) (*connect.Response[v1.ListLessonsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.ListLessons is not implemented"))
}

func (UnimplementedCourseServiceHandler) ReorderLessons(context.Context, *connect.Request[v1.ReorderLessonsRequest]) (*connect.Response[v1.ReorderLessonsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.ReorderLessons is not implemented"))
}

func (UnimplementedCourseServiceHandler) EnrollUser(context.Context, *connect.Request[v1.EnrollUserRequest]) (*connect.Response[v1.EnrollUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.EnrollUser is not implemented"))
}

func (UnimplementedCourseServiceHandler) GetEnrollment(context.Context, *connect.Request[v1.GetEnrollmentRequest]) (*connect.Response[v1.GetEnrollmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.GetEnrollment is not implemented"))
}

func (UnimplementedCourseServiceHandler) UpdateProgress(context.Context, *connect.Request[v1.UpdateProgressRequest]) (*connect.Response[v1.UpdateProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.UpdateProgress is not implemented"))
}

func (UnimplementedCourseServiceHandler) ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.ListEnrollments is not implemented"))
}

func (UnimplementedCourseServiceHandler) SetPricing(context.Context, *connect.Request[v1.SetPricingRequest]) (*connect.Response[v1.SetPricingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.SetPricing is not implemented"))
}

func (UnimplementedCourseServiceHandler) GetPricing(context.Context, *connect.Request[v1.GetPricingRequest]) (*connect.Response[v1.GetPricingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.GetPricing is not implemented"))
}
