// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: thanawy/v1/course.proto

package thanawyv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
	v1 "thanawy-backend/internal/proto/thanawy/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CourseServiceName is the fully-qualified name of the CourseService service.
	CourseServiceName = "thanawy.v1.CourseService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CourseServiceGetCoursesProcedure is the fully-qualified name of the CourseService's GetCourses
	// RPC.
	CourseServiceGetCoursesProcedure = "/thanawy.v1.CourseService/GetCourses"
	// CourseServiceGetCourseProcedure is the fully-qualified name of the CourseService's GetCourse RPC.
	CourseServiceGetCourseProcedure = "/thanawy.v1.CourseService/GetCourse"
)

// CourseServiceClient is a client for the thanawy.v1.CourseService service.
type CourseServiceClient interface {
	GetCourses(context.Context, *connect.Request[v1.GetCoursesRequest]) (*connect.Response[v1.GetCoursesResponse], error)
	GetCourse(context.Context, *connect.Request[v1.GetCourseRequest]) (*connect.Response[v1.GetCourseResponse], error)
}

// NewCourseServiceClient constructs a client for the thanawy.v1.CourseService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCourseServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CourseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	courseServiceMethods := v1.File_thanawy_v1_course_proto.Services().ByName("CourseService").Methods()
	return &courseServiceClient{
		getCourses: connect.NewClient[v1.GetCoursesRequest, v1.GetCoursesResponse](
			httpClient,
			baseURL+CourseServiceGetCoursesProcedure,
			connect.WithSchema(courseServiceMethods.ByName("GetCourses")),
			connect.WithClientOptions(opts...),
		),
		getCourse: connect.NewClient[v1.GetCourseRequest, v1.GetCourseResponse](
			httpClient,
			baseURL+CourseServiceGetCourseProcedure,
			connect.WithSchema(courseServiceMethods.ByName("GetCourse")),
			connect.WithClientOptions(opts...),
		),
	}
}

// courseServiceClient implements CourseServiceClient.
type courseServiceClient struct {
	getCourses *connect.Client[v1.GetCoursesRequest, v1.GetCoursesResponse]
	getCourse  *connect.Client[v1.GetCourseRequest, v1.GetCourseResponse]
}

// GetCourses calls thanawy.v1.CourseService.GetCourses.
func (c *courseServiceClient) GetCourses(ctx context.Context, req *connect.Request[v1.GetCoursesRequest]) (*connect.Response[v1.GetCoursesResponse], error) {
	return c.getCourses.CallUnary(ctx, req)
}

// GetCourse calls thanawy.v1.CourseService.GetCourse.
func (c *courseServiceClient) GetCourse(ctx context.Context, req *connect.Request[v1.GetCourseRequest]) (*connect.Response[v1.GetCourseResponse], error) {
	return c.getCourse.CallUnary(ctx, req)
}

// CourseServiceHandler is an implementation of the thanawy.v1.CourseService service.
type CourseServiceHandler interface {
	GetCourses(context.Context, *connect.Request[v1.GetCoursesRequest]) (*connect.Response[v1.GetCoursesResponse], error)
	GetCourse(context.Context, *connect.Request[v1.GetCourseRequest]) (*connect.Response[v1.GetCourseResponse], error)
}

// NewCourseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCourseServiceHandler(svc CourseServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	courseServiceMethods := v1.File_thanawy_v1_course_proto.Services().ByName("CourseService").Methods()
	courseServiceGetCoursesHandler := connect.NewUnaryHandler(
		CourseServiceGetCoursesProcedure,
		svc.GetCourses,
		connect.WithSchema(courseServiceMethods.ByName("GetCourses")),
		connect.WithHandlerOptions(opts...),
	)
	courseServiceGetCourseHandler := connect.NewUnaryHandler(
		CourseServiceGetCourseProcedure,
		svc.GetCourse,
		connect.WithSchema(courseServiceMethods.ByName("GetCourse")),
		connect.WithHandlerOptions(opts...),
	)
	return "/thanawy.v1.CourseService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CourseServiceGetCoursesProcedure:
			courseServiceGetCoursesHandler.ServeHTTP(w, r)
		case CourseServiceGetCourseProcedure:
			courseServiceGetCourseHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCourseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCourseServiceHandler struct{}

func (UnimplementedCourseServiceHandler) GetCourses(context.Context, *connect.Request[v1.GetCoursesRequest]) (*connect.Response[v1.GetCoursesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.GetCourses is not implemented"))
}

func (UnimplementedCourseServiceHandler) GetCourse(context.Context, *connect.Request[v1.GetCourseRequest]) (*connect.Response[v1.GetCourseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("thanawy.v1.CourseService.GetCourse is not implemented"))
}
