-- =============================================================
-- 0168: add permissions.action and seed the permission catalog
--
-- The Permission model (and the admin roles UI which reads
-- /api/admin/permissions) expect a module/action split, but the
-- permissions table created in 0059 only had name/module/
-- description. This migration adds the missing action column
-- and backfills/inserts the canonical module:action catalog
-- defined by the Perm* constants in internal/domain/common.
-- =============================================================

ALTER TABLE permissions ADD COLUMN IF NOT EXISTS action VARCHAR(50) NOT NULL DEFAULT '';

-- Backfill action/module for any pre-existing rows stored as module:action.
UPDATE permissions SET action = split_part(name, ':', 2), module = split_part(name, ':', 1)
WHERE name LIKE '%:%' AND (action = '' OR action IS NULL);

-- Permission catalog (source: AllPermissions() / Perm* constants).
INSERT INTO permissions (name, module, action, description) VALUES
 ('ab_testing:view','ab_testing','view',NULL),
 ('achievements:manage','achievements','manage',NULL),
 ('achievements:view','achievements','view',NULL),
 ('admin:bypass','admin','bypass',NULL),
 ('ai:manage','ai','manage',NULL),
 ('ai:usage','ai','usage',NULL),
 ('analytics:view','analytics','view',NULL),
 ('announcements:manage','announcements','manage',NULL),
 ('announcements:view','announcements','view',NULL),
 ('audit_logs:view','audit_logs','view',NULL),
 ('blog:create','blog','create',NULL),
 ('blog:delete','blog','delete',NULL),
 ('blog:manage','blog','manage',NULL),
 ('blog:publish','blog','publish',NULL),
 ('blog:update','blog','update',NULL),
 ('blog:view','blog','view',NULL),
 ('books:create','books','create',NULL),
 ('books:delete','books','delete',NULL),
 ('books:manage','books','manage',NULL),
 ('books:publish','books','publish',NULL),
 ('books:update','books','update',NULL),
 ('books:view','books','view',NULL),
 ('challenges:manage','challenges','manage',NULL),
 ('challenges:view','challenges','view',NULL),
 ('children:attendance','children','attendance',NULL),
 ('children:communicate','children','communicate',NULL),
 ('children:grades','children','grades',NULL),
 ('children:payment','children','payment',NULL),
 ('children:progress','children','progress',NULL),
 ('children:view','children','view',NULL),
 ('comments:create','comments','create',NULL),
 ('comments:moderate','comments','moderate',NULL),
 ('comments:view','comments','view',NULL),
 ('contests:manage','contests','manage',NULL),
 ('contests:view','contests','view',NULL),
 ('dashboard:access','dashboard','access',NULL),
 ('dashboard:acknowledge_alerts','dashboard','acknowledge_alerts',NULL),
 ('dashboard:apply_saved_filters','dashboard','apply_saved_filters',NULL),
 ('dashboard:delete_saved_filters','dashboard','delete_saved_filters',NULL),
 ('dashboard:export','dashboard','export',NULL),
 ('dashboard:manage','dashboard','manage',NULL),
 ('dashboard:refresh_cache','dashboard','refresh_cache',NULL),
 ('dashboard:save_filters','dashboard','save_filters',NULL),
 ('dashboard:view','dashboard','view',NULL),
 ('dashboard:view_alerts','dashboard','view_alerts',NULL),
 ('dashboard:view_content_metrics','dashboard','view_content_metrics',NULL),
 ('dashboard:view_exports','dashboard','view_exports',NULL),
 ('dashboard:view_financial_metrics','dashboard','view_financial_metrics',NULL),
 ('dashboard:view_kpis','dashboard','view_kpis',NULL),
 ('dashboard:view_learning_metrics','dashboard','view_learning_metrics',NULL),
 ('dashboard:view_pending_items','dashboard','view_pending_items',NULL),
 ('dashboard:view_recent_activity','dashboard','view_recent_activity',NULL),
 ('dashboard:view_sensitive_metrics','dashboard','view_sensitive_metrics',NULL),
 ('dashboard:view_support_metrics','dashboard','view_support_metrics',NULL),
 ('dashboard:view_system_health','dashboard','view_system_health',NULL),
 ('dashboard:view_top_courses','dashboard','view_top_courses',NULL),
 ('events:manage','events','manage',NULL),
 ('events:view','events','view',NULL),
 ('exams:approve','exams','approve',NULL),
 ('exams:create','exams','create',NULL),
 ('exams:delete','exams','delete',NULL),
 ('exams:manage','exams','manage',NULL),
 ('exams:publish','exams','publish',NULL),
 ('exams:update','exams','update',NULL),
 ('exams:view','exams','view',NULL),
 ('faqs:manage','faqs','manage',NULL),
 ('forum:create','forum','create',NULL),
 ('forum:delete','forum','delete',NULL),
 ('forum:manage','forum','manage',NULL),
 ('forum:moderate','forum','moderate',NULL),
 ('forum:update','forum','update',NULL),
 ('forum:view','forum','view',NULL),
 ('live_monitor:view','live_monitor','view',NULL),
 ('marketing:manage','marketing','manage',NULL),
 ('marketing:view','marketing','view',NULL),
 ('notifications:manage','notifications','manage',NULL),
 ('notifications:send','notifications','send',NULL),
 ('own_books:manage','own_books','manage',NULL),
 ('own_challenges:manage','own_challenges','manage',NULL),
 ('own_exams:manage','own_exams','manage',NULL),
 ('own_resources:manage','own_resources','manage',NULL),
 ('own_subjects:manage','own_subjects','manage',NULL),
 ('parents:manage','parents','manage',NULL),
 ('parents:view','parents','view',NULL),
 ('permissions:custom','permissions','custom',NULL),
 ('reports:manage','reports','manage',NULL),
 ('reports:view','reports','view',NULL),
 ('resources:manage','resources','manage',NULL),
 ('resources:publish','resources','publish',NULL),
 ('resources:view','resources','view',NULL),
 ('rewards:manage','rewards','manage',NULL),
 ('rewards:view','rewards','view',NULL),
 ('seasons:manage','seasons','manage',NULL),
 ('seasons:view','seasons','view',NULL),
 ('settings:view','settings','view',NULL),
 ('students:manage','students','manage',NULL),
 ('students:view','students','view',NULL),
 ('subjects:approve','subjects','approve',NULL),
 ('subjects:create','subjects','create',NULL),
 ('subjects:delete','subjects','delete',NULL),
 ('subjects:manage','subjects','manage',NULL),
 ('subjects:publish','subjects','publish',NULL),
 ('subjects:update','subjects','update',NULL),
 ('subjects:view','subjects','view',NULL),
 ('system:manage','system','manage',NULL),
 ('system:settings','system','settings',NULL),
 ('teachers:manage','teachers','manage',NULL),
 ('teachers:view','teachers','view',NULL),
 ('tickets:create','tickets','create',NULL),
 ('tickets:manage','tickets','manage',NULL),
 ('tickets:resolve','tickets','resolve',NULL),
 ('tickets:update','tickets','update',NULL),
 ('tickets:view','tickets','view',NULL),
 ('users:create','users','create',NULL),
 ('users:delete','users','delete',NULL),
 ('users:export','users','export',NULL),
 ('users:impersonate','users','impersonate',NULL),
 ('users:import','users','import',NULL),
 ('users:manage','users','manage',NULL),
 ('users:update','users','update',NULL),
 ('users:view','users','view',NULL)
ON CONFLICT (name) DO UPDATE SET module = EXCLUDED.module, action = EXCLUDED.action;

-- Support the admin permission lists/grouping queries.
CREATE INDEX IF NOT EXISTS idx_permissions_module_name ON permissions (module, name);
