// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: thanawy/v1/analytics.proto

package thanawyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetProgressSummary_FullMethodName = "/thanawy.v1.AnalyticsService/GetProgressSummary"
	AnalyticsService_GetWeeklyAnalytics_FullMethodName = "/thanawy.v1.AnalyticsService/GetWeeklyAnalytics"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetProgressSummary(ctx context.Context, in *GetProgressSummaryRequest, opts ...grpc.CallOption) (*GetProgressSummaryResponse, error)
	GetWeeklyAnalytics(ctx context.Context, in *GetWeeklyAnalyticsRequest, opts ...grpc.CallOption) (*GetWeeklyAnalyticsResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetProgressSummary(ctx context.Context, in *GetProgressSummaryRequest, opts ...grpc.CallOption) (*GetProgressSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProgressSummaryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetProgressSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetWeeklyAnalytics(ctx context.Context, in *GetWeeklyAnalyticsRequest, opts ...grpc.CallOption) (*GetWeeklyAnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeeklyAnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetWeeklyAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetProgressSummary(context.Context, *GetProgressSummaryRequest) (*GetProgressSummaryResponse, error)
	GetWeeklyAnalytics(context.Context, *GetWeeklyAnalyticsRequest) (*GetWeeklyAnalyticsResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetProgressSummary(context.Context, *GetProgressSummaryRequest) (*GetProgressSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgressSummary not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetWeeklyAnalytics(context.Context, *GetWeeklyAnalyticsRequest) (*GetWeeklyAnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeeklyAnalytics not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {
	// This method is intentionally left empty to ensure that any implementation of AnalyticsServiceServer
	// embeds this struct for forward compatibility.
}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue() {
	// This method is intentionally left empty and is used by the gRPC-Go framework to
	// verify that the server implementation is embedded by value rather than by pointer.
}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetProgressSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetProgressSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetProgressSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetProgressSummary(ctx, req.(*GetProgressSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetWeeklyAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetWeeklyAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetWeeklyAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetWeeklyAnalytics(ctx, req.(*GetWeeklyAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thanawy.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProgressSummary",
			Handler:    _AnalyticsService_GetProgressSummary_Handler,
		},
		{
			MethodName: "GetWeeklyAnalytics",
			Handler:    _AnalyticsService_GetWeeklyAnalytics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thanawy/v1/analytics.proto",
}
