// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: thanawy/v1/analytics.proto

package thanawyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProgressSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressSummaryRequest) Reset() {
	*x = GetProgressSummaryRequest{}
	mi := &file_thanawy_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressSummaryRequest) ProtoMessage() {}

func (x *GetProgressSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetProgressSummaryRequest) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_analytics_proto_rawDescGZIP(), []int{0}
}

type GetProgressSummaryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalMinutes   int32                  `protobuf:"varint,1,opt,name=total_minutes,json=totalMinutes,proto3" json:"total_minutes,omitempty"`
	AverageFocus   float64                `protobuf:"fixed64,2,opt,name=average_focus,json=averageFocus,proto3" json:"average_focus,omitempty"`
	TasksCompleted int64                  `protobuf:"varint,3,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	StreakDays     int32                  `protobuf:"varint,4,opt,name=streak_days,json=streakDays,proto3" json:"streak_days,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProgressSummaryResponse) Reset() {
	*x = GetProgressSummaryResponse{}
	mi := &file_thanawy_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressSummaryResponse) ProtoMessage() {}

func (x *GetProgressSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetProgressSummaryResponse) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetProgressSummaryResponse) GetTotalMinutes() int32 {
	if x != nil {
		return x.TotalMinutes
	}
	return 0
}

func (x *GetProgressSummaryResponse) GetAverageFocus() float64 {
	if x != nil {
		return x.AverageFocus
	}
	return 0
}

func (x *GetProgressSummaryResponse) GetTasksCompleted() int64 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *GetProgressSummaryResponse) GetStreakDays() int32 {
	if x != nil {
		return x.StreakDays
	}
	return 0
}

type GetWeeklyAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyAnalyticsRequest) Reset() {
	*x = GetWeeklyAnalyticsRequest{}
	mi := &file_thanawy_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyAnalyticsRequest) ProtoMessage() {}

func (x *GetWeeklyAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*GetWeeklyAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_analytics_proto_rawDescGZIP(), []int{2}
}

type DailyProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           string                 `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyProgress) Reset() {
	*x = DailyProgress{}
	mi := &file_thanawy_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyProgress) ProtoMessage() {}

func (x *DailyProgress) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyProgress.ProtoReflect.Descriptor instead.
func (*DailyProgress) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DailyProgress) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *DailyProgress) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type GetWeeklyAnalyticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgressRate   int32                  `protobuf:"varint,1,opt,name=progress_rate,json=progressRate,proto3" json:"progress_rate,omitempty"`
	SkillsAcquired int32                  `protobuf:"varint,2,opt,name=skills_acquired,json=skillsAcquired,proto3" json:"skills_acquired,omitempty"`
	StudyHours     int32                  `protobuf:"varint,3,opt,name=study_hours,json=studyHours,proto3" json:"study_hours,omitempty"`
	DailyProgress  []*DailyProgress       `protobuf:"bytes,4,rep,name=daily_progress,json=dailyProgress,proto3" json:"daily_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetWeeklyAnalyticsResponse) Reset() {
	*x = GetWeeklyAnalyticsResponse{}
	mi := &file_thanawy_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyAnalyticsResponse) ProtoMessage() {}

func (x *GetWeeklyAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GetWeeklyAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetWeeklyAnalyticsResponse) GetProgressRate() int32 {
	if x != nil {
		return x.ProgressRate
	}
	return 0
}

func (x *GetWeeklyAnalyticsResponse) GetSkillsAcquired() int32 {
	if x != nil {
		return x.SkillsAcquired
	}
	return 0
}

func (x *GetWeeklyAnalyticsResponse) GetStudyHours() int32 {
	if x != nil {
		return x.StudyHours
	}
	return 0
}

func (x *GetWeeklyAnalyticsResponse) GetDailyProgress() []*DailyProgress {
	if x != nil {
		return x.DailyProgress
	}
	return nil
}

var File_thanawy_v1_analytics_proto protoreflect.FileDescriptor

const file_thanawy_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1athanawy/v1/analytics.proto\x12\n" +
	"thanawy.v1\"\x1b\n" +
	"\x19GetProgressSummaryRequest\"\xb0\x01\n" +
	"\x1aGetProgressSummaryResponse\x12#\n" +
	"\rtotal_minutes\x18\x01 \x01(\x05R\ftotalMinutes\x12#\n" +
	"\raverage_focus\x18\x02 \x01(\x01R\faverageFocus\x12'\n" +
	"\x0ftasks_completed\x18\x03 \x01(\x03R\x0etasksCompleted\x12\x1f\n" +
	"\vstreak_days\x18\x04 \x01(\x05R\n" +
	"streakDays\"\x1b\n" +
	"\x19GetWeeklyAnalyticsRequest\"=\n" +
	"\rDailyProgress\x12\x10\n" +
	"\x03day\x18\x01 \x01(\tR\x03day\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\"\xcd\x01\n" +
	"\x1aGetWeeklyAnalyticsResponse\x12#\n" +
	"\rprogress_rate\x18\x01 \x01(\x05R\fprogressRate\x12'\n" +
	"\x0fskills_acquired\x18\x02 \x01(\x05R\x0eskillsAcquired\x12\x1f\n" +
	"\vstudy_hours\x18\x03 \x01(\x05R\n" +
	"studyHours\x12@\n" +
	"\x0edaily_progress\x18\x04 \x03(\v2\x19.thanawy.v1.DailyProgressR\rdailyProgress2\xdc\x01\n" +
	"\x10AnalyticsService\x12c\n" +
	"\x12GetProgressSummary\x12%.thanawy.v1.GetProgressSummaryRequest\x1a&.thanawy.v1.GetProgressSummaryResponse\x12c\n" +
	"\x12GetWeeklyAnalytics\x12%.thanawy.v1.GetWeeklyAnalyticsRequest\x1a&.thanawy.v1.GetWeeklyAnalyticsResponseB5Z3thanawy-backend/internal/proto/thanawy/v1;thanawyv1b\x06proto3"

var (
	file_thanawy_v1_analytics_proto_rawDescOnce sync.Once
	file_thanawy_v1_analytics_proto_rawDescData []byte
)

func file_thanawy_v1_analytics_proto_rawDescGZIP() []byte {
	file_thanawy_v1_analytics_proto_rawDescOnce.Do(func() {
		file_thanawy_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thanawy_v1_analytics_proto_rawDesc), len(file_thanawy_v1_analytics_proto_rawDesc)))
	})
	return file_thanawy_v1_analytics_proto_rawDescData
}

var file_thanawy_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_thanawy_v1_analytics_proto_goTypes = []any{
	(*GetProgressSummaryRequest)(nil),  // 0: thanawy.v1.GetProgressSummaryRequest
	(*GetProgressSummaryResponse)(nil), // 1: thanawy.v1.GetProgressSummaryResponse
	(*GetWeeklyAnalyticsRequest)(nil),  // 2: thanawy.v1.GetWeeklyAnalyticsRequest
	(*DailyProgress)(nil),              // 3: thanawy.v1.DailyProgress
	(*GetWeeklyAnalyticsResponse)(nil), // 4: thanawy.v1.GetWeeklyAnalyticsResponse
}
var file_thanawy_v1_analytics_proto_depIdxs = []int32{
	3, // 0: thanawy.v1.GetWeeklyAnalyticsResponse.daily_progress:type_name -> thanawy.v1.DailyProgress
	0, // 1: thanawy.v1.AnalyticsService.GetProgressSummary:input_type -> thanawy.v1.GetProgressSummaryRequest
	2, // 2: thanawy.v1.AnalyticsService.GetWeeklyAnalytics:input_type -> thanawy.v1.GetWeeklyAnalyticsRequest
	1, // 3: thanawy.v1.AnalyticsService.GetProgressSummary:output_type -> thanawy.v1.GetProgressSummaryResponse
	4, // 4: thanawy.v1.AnalyticsService.GetWeeklyAnalytics:output_type -> thanawy.v1.GetWeeklyAnalyticsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_thanawy_v1_analytics_proto_init() }
func file_thanawy_v1_analytics_proto_init() {
	if File_thanawy_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thanawy_v1_analytics_proto_rawDesc), len(file_thanawy_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thanawy_v1_analytics_proto_goTypes,
		DependencyIndexes: file_thanawy_v1_analytics_proto_depIdxs,
		MessageInfos:      file_thanawy_v1_analytics_proto_msgTypes,
	}.Build()
	File_thanawy_v1_analytics_proto = out.File
	file_thanawy_v1_analytics_proto_goTypes = nil
	file_thanawy_v1_analytics_proto_depIdxs = nil
}
