// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: thanawy/v1/course.proto

package thanawyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TeacherName   string                 `protobuf:"bytes,4,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_thanawy_v1_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {
	// ProtoMessage is a marker method for the proto.Message interface.
}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

type GetCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	mi := &file_thanawy_v1_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {
	// ProtoMessage is a marker method for the proto.Message interface.
}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_course_proto_rawDescGZIP(), []int{1}
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	mi := &file_thanawy_v1_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {
	// ProtoMessage is a marker method for the proto.Message interface.
}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_course_proto_rawDescGZIP(), []int{2}
}

func (x *GetCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_thanawy_v1_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {
	// ProtoMessage is a marker method for the proto.Message interface.
}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_course_proto_rawDescGZIP(), []int{3}
}

func (x *GetCourseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseResponse) Reset() {
	*x = GetCourseResponse{}
	mi := &file_thanawy_v1_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResponse) ProtoMessage() {
	// ProtoMessage is a marker method for the proto.Message interface.
}

func (x *GetCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thanawy_v1_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResponse.ProtoReflect.Descriptor instead.
func (*GetCourseResponse) Descriptor() ([]byte, []int) {
	return file_thanawy_v1_course_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

var File_thanawy_v1_course_proto protoreflect.FileDescriptor

const file_thanawy_v1_course_proto_rawDesc = "" +
	"\n" +
	"\x17thanawy/v1/course.proto\x12\n" +
	"thanawy.v1\"s\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fteacher_name\x18\x04 \x01(\tR\vteacherName\"\x13\n" +
	"\x11GetCoursesRequest\"B\n" +
	"\x12GetCoursesResponse\x12,\n" +
	"\acourses\x18\x01 \x03(\v2\x12.thanawy.v1.CourseR\acourses\"\"\n" +
	"\x10GetCourseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x11GetCourseResponse\x12*\n" +
	"\x06course\x18\x01 \x01(\v2\x12.thanawy.v1.CourseR\x06course2\xa6\x01\n" +
	"\rCourseService\x12K\n" +
	"\n" +
	"GetCourses\x12\x1d.thanawy.v1.GetCoursesRequest\x1a\x1e.thanawy.v1.GetCoursesResponse\x12H\n" +
	"\tGetCourse\x12\x1c.thanawy.v1.GetCourseRequest\x1a\x1d.thanawy.v1.GetCourseResponseB5Z3thanawy-backend/internal/proto/thanawy/v1;thanawyv1b\x06proto3"

var (
	file_thanawy_v1_course_proto_rawDescOnce sync.Once
	file_thanawy_v1_course_proto_rawDescData []byte
)

func file_thanawy_v1_course_proto_rawDescGZIP() []byte {
	file_thanawy_v1_course_proto_rawDescOnce.Do(func() {
		file_thanawy_v1_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thanawy_v1_course_proto_rawDesc), len(file_thanawy_v1_course_proto_rawDesc)))
	})
	return file_thanawy_v1_course_proto_rawDescData
}

var file_thanawy_v1_course_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_thanawy_v1_course_proto_goTypes = []any{
	(*Course)(nil),             // 0: thanawy.v1.Course
	(*GetCoursesRequest)(nil),  // 1: thanawy.v1.GetCoursesRequest
	(*GetCoursesResponse)(nil), // 2: thanawy.v1.GetCoursesResponse
	(*GetCourseRequest)(nil),   // 3: thanawy.v1.GetCourseRequest
	(*GetCourseResponse)(nil),  // 4: thanawy.v1.GetCourseResponse
}
var file_thanawy_v1_course_proto_depIdxs = []int32{
	0, // 0: thanawy.v1.GetCoursesResponse.courses:type_name -> thanawy.v1.Course
	0, // 1: thanawy.v1.GetCourseResponse.course:type_name -> thanawy.v1.Course
	1, // 2: thanawy.v1.CourseService.GetCourses:input_type -> thanawy.v1.GetCoursesRequest
	3, // 3: thanawy.v1.CourseService.GetCourse:input_type -> thanawy.v1.GetCourseRequest
	2, // 4: thanawy.v1.CourseService.GetCourses:output_type -> thanawy.v1.GetCoursesResponse
	4, // 5: thanawy.v1.CourseService.GetCourse:output_type -> thanawy.v1.GetCourseResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_thanawy_v1_course_proto_init() }
func file_thanawy_v1_course_proto_init() {
	if File_thanawy_v1_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thanawy_v1_course_proto_rawDesc), len(file_thanawy_v1_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thanawy_v1_course_proto_goTypes,
		DependencyIndexes: file_thanawy_v1_course_proto_depIdxs,
		MessageInfos:      file_thanawy_v1_course_proto_msgTypes,
	}.Build()
	File_thanawy_v1_course_proto = out.File
	file_thanawy_v1_course_proto_goTypes = nil
	file_thanawy_v1_course_proto_depIdxs = nil
}
